# Generated by Django 6.0.2 on 2026-02-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airqualityreport",
            name="device_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
